- Makefile
This PR fixes typo on Makefile
> Fix: typo serve→start

- .github/workflows/lint-backend.yaml
- .github/workflows/test-backend.yaml
- Makefile
> GitHub Actions for backend (test and lint)

- README.md
> Update README.md about memory allocation to Docker

- OWNERS
/cc @adtac 
/cc @Huang-Wei 
/cc @alculquicondor 
Hello team :)
Add sanposhiho to approvers.
(a similar reason to https://github.com/kubernetes/org/pull/3054)
In order to approve changes of technical parts especially. -- Probably no one else besides me can review the technical changes for now.
like:
- https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/36
- https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/25
> Add sanposhiho to approvers

- docker-compose.yml
fix #23 
- Set environment variable `HOST=0.0.0.0` to  simulator-frontend in docker-compse.yaml
> Set environment variable HOST=0.0.0.0 to  simulator-frontend in docker-compse.yaml

- web/Dockerfile
current latest node image is Node.js version v17. Using latest image should break codes unexpectedly.
Also, odd-numbered releases of Node.js is [short term version](https://nodejs.org/en/about/releases/).
Related: https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/38
> pin node image to Node.js v16

- .gitmodules
Jobs post-kube-scheduler-simulator-push were failed.
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kube-scheduler-simulator-push-images/1456617270737375232
error log:
```
$ git submodule update --init --recursive
Submodule 'submodules/kubernetes' (git@github.com:kubernetes/kubernetes.git) registered for path 'submodules/kubernetes'
Cloning into '/home/prow/go/src/github.com/kubernetes-sigs/kube-scheduler-simulator/submodules/kubernetes'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:kubernetes/kubernetes.git' into submodule path '/home/prow/go/src/github.com/kubernetes-sigs/kube-scheduler-simulator/submodules/kubernetes' …
```
> use https instead of ssh for submodule

- cloudbuild.yaml
part of #19 
guide: https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md
For the most part, it is almost the same as the example in the guide.
> Support build with cloudbuild for gcr

- cloudbuild.yaml
Hello. 
Sorry, I forgot to add `'` at some ends on `cloudbuild.yaml` in #21  🤦‍♂️
```
ERROR: (gcloud.builds.submit) parsing /home/prow/go/src/github.com/kubernetes-sigs/kube-scheduler-simulator/cloudbuild.yaml: while parsing a block collection
in "/home/prow/go/src/github.com/kubernetes-sigs/kube-scheduler-simulator/cloudbuild.yaml", line 29, column 3
expected <block end>, but found '<scalar>'
in "/home/prow/go/src/github.com/kubernetes-sigs/kube-scheduler-simulator/cloudbuild.yaml", line 31, column 6
```
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kube-scheduler-simulator-push-images/1468300940288200704
> Fix syntax error on cloudbuild.yaml

- server/server.go
Fix the lint (funlen) issue on `NewSimulatorServer` with `//nolint` directive.
This problem is due to the fact that GitHub Action does not work for first contributor's PR. This will be resolved with #56.
Fixes #
> Fix the lint issue on `NewSimulatorServer` with nolint directive

- cloudbuild.yaml
/kind bug
```
Your build timed out. Use the [--timeout=DURATION] flag to change the timeout threshold.
ERROR: (gcloud.builds.submit) build 1aaf01c6-a2fc-4a43-8e66-5aed461643b8 completed with status "TIMEOUT"
```
Not enough time for frontend build.
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kube-scheduler-simulator-push-images/1472567754648195072
Ref #19 
> extend timeout for cloud build

- web/api/v1/node.ts
- web/api/v1/pod.ts
- web/api/v1/priorityclass.ts
- web/api/v1/pv.ts
- web/api/v1/pvc.ts
- web/api/v1/schedulerconfiguration.ts
- web/api/v1/storageclass.ts
- web/components/PriorityClassList.vue
- web/components/ResourceAddButton.vue
- web/components/ResourceBar/ResourceBar.vue
- web/components/StoreKey/PriorityClassStoreKey.ts
- web/components/StoreProvider/PriorityClassStoreProvider.vue
- web/components/lib/template.ts
- web/components/lib/templates/priorityclass.yaml
- web/nuxt.config.js
- web/pages/index.vue
- web/store/priorityclass.ts
/kind feature
Add frontend to consume api for priorityclass from backend.
Related #27 
Fixes #27 
Just a question, was I supposed to separate PRs by making two separate branches (with separate commits only relevant for PR, like here) or make two branches that might share some code and commits: for example, I leave same previous branch and create a branch on commit where work on backend ended and branch on commit where work on frontend ended and make PRs for both? What are the best practices to follow next time? 
This is the front end commits after separating them from branch previous branch (front end won't work since it requires back end changes to be present).
(Answered)
> support PriorityClass on frontend

- Makefile
/kind feature
As part of this change, we are adding an entry into the Makefile to include `go-mod downloads` so that those can be referred into prow job configs.
Fixes #56 
This is a WIP PR
> Update makefile for go-mod downloads

- .golangci.yml
- scheduler/plugin/plugins.go
- scheduler/plugin/plugins_test.go
Hi team~
Fixes: #12 
This PR fixes the bug on restarting scheduler. 
The function NewPluginConfig failed to override configuration correctly when passed PluginConfig has args data on PluginConfig.Args.Raw not on PluginConfig.Args.Object. So, fixed it
/kind bug
> override configuration correctly, even if passed PluginConfig has args data on PluginConfig.Args.Raw

- config/config.go
- config/config_test.go
- scheduler/scheduler.go
- server/di/di.go
- simulator.go
/kind feature
Add initial scheduler configuration from file path taken from environment variable.
Fixes #37
I've confirmed that it also worked when I passed configuration file path.
I'd like to learn more so correcting my every little mistake is welcome!
> support initial scheduler configuration option via an environment variable

- web/components/ResourceBar/ResourceBar.vue
Fixes #10 
It seems that v-data-table(vuetify component used to show table) cannot scroll horizontally when the v-navigation-drawer cannot be scrolled vertically 🤔  and it causes bug #10.
I add `<div>` with height as hot fix so that v-navigation-drawer always can be scrolled vertically.
/kind bug
> Workaround: v-data-table cannot scroll when the bar cannot be scrolled vertically

- go.mod
- node/mock_node/node.go
- node/node.go
- node/node_test.go
- persistentvolume/persistentvolume.go
- persistentvolumeclaim/persistentvolumeclaim.go
- pod/pod.go
- pod/pod_test.go
- priorityclass/priorityclass.go
- server/di/interface.go
- storageclass/storageclass.go
/kind feature
I added delete all resources of each objects.
Fixes #67
> add resources "delete all" method in each service

- web/components/ResourceBar/ResourceBar.vue
/kind bug
This error is detected by frontend linter, so I fixed it.
nope
> Fix lint error of ResourceBar

- web/Dockerfile
Signed-off-by: skuethe <56306041+skuethe@users.noreply.github.com>
/kind bug
This PR adds the required `nuxt` telementry user input via env variable during the container image build. Without this input
Fixes #87 
There are two possibilities to avoid the telemetry user input during startup:
https://github.com/nuxt/telemetry#opting-out
1. modify a setting in a `nuxt.config`
2. set an environment var
I tried to modify the file `web/nuxt.config.js` and then re-enable to copy command in the `web/Dockerfile`, but that does seem to create a lot of other issues.
So this PR is setting the env var in the `web/Dockerfile`.
> fix(frontend): react on nuxt telemetry user input during `yarn start`

- config/config.go
- k8sapiserver/k8sapiserver.go
- simulator.go
/kind feature #55 
This PR addresses the feature request #55 , it allows user to use kubectl to interact with the API server by specifying the --server flag pointed to the opened port.
N/A
> add configuration to change the URL of kube-apiserver

- web/components/ResourceBar/ResourceBar.vue
- web/store/node.ts
- web/store/pod.ts
- web/store/priorityclass.ts
- web/store/pv.ts
- web/store/pvc.ts
- web/store/schedulerconfiguration.ts
- web/store/storageclass.ts
/kind feature
We turn off the delete button when the selected `priorityclass` is created by k8s.
- The name of it prefixed with `system-` is reserved by the system and it can't be deleted.
[Reference](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#how-to-use-priority-and-preemption)
To implement that logic, we added a new field on` SelectedItem` interface.
Fixes #99
For the general
For the system
Even now, the apply/edit button is still enabled.
This is because even if the `PriorityClass` is the system one, `description` field, for example, is editable.
> Disable the delete button when the selected `priorityclass` is the system one

- config/config.go
- server/di/di.go
- simulator.go
/kind feature
Add `EXTERNAL_IMPORT_ENABLED` environment variables it indicates whether the scheduler should enable the function to import from an existing cluster.
Eventually, we would like to implement https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/41 .
Relates #41
> Add `EXTERNAL_IMPORT_ENABLED` environment variables

- export/export.go
- export/export_test.go
- server/di/interface.go
- server/handler/export.go
/kind feature
/kind api-change
Support to `WithIgnoreErr` option in the export service. 
Eventually, we would like to implement https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/41 .
> When this is passed, `export/import` method shouldn't return errors and log the error instead.
> - The simulator may only be able to get some of the resources due to lack of permissions or other reasons.
> - And some users may want to import just some of the resources from an existing cluster.
Relates #41
> Support to `WithIgnoreErr` option in the `ExportService`

- scheduler/plugin/resultstore/store.go
/kind bug
Fixes a race condition in the Store struct located in the resultstore package
There is no issue opened for this bug 
I've been using the simulator to test different scheduler configurations starting from a existing cluster status. In order to do that, I am mocking the status of the cluster in the simulator creating equivalent nodes in the original cluster and forcing pods to be placed in the same nodes. Since my clusters have a lot of nodes and pods, I've created some scripts to load the existing cluster and by doing this I've found out a race condition
* Start the simulator (both bare metal and docker-compose version should work)
* Create a huge amount of pods in a short period of time. This script can be used to do that …
> Fix race condition in store result map

- export/export.go
- export/export_test.go
/kind bug
The `priorityclass`, `system-cluster-critical` and `system-node-critical`, are created automatically, but it can't delete and is unable to modify some fields.
The name of PriorityClass that is prefixed with `system-`, is reserved by the system.
So, we add filtering logic to `import/export` functions.
Fixes #98
https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#how-to-use-priority-and-preemption
/assign @sanposhiho
> Add filtering logic for a `PriorityClass` that the name  is prefixed with `system-`

- export/export_test.go
- server/handler/export.go
/kind bug
In #103, I have added the `IgnoreErr` option to the `Import/Export` functions called via web API.
But the `IgnoreErr` option was going to use for another logic (Only for Importing the existing Cluster's resources.)
When we call it via web API, it should return an error if an error has occurred.
Since the current usage of the function is incorrect, I fixed it.
And also, I found a typo in the test function's name.
Fixes #103
> Remove `IgnoreErr` options from  the `Import/Export` function called via web API

- web/components/ResourceBar/ResourceBar.vue
/kind bug
add check if Node has Pods or not before deleting scheduled Pods on Node
Fixes #145
> add check if Node has Pods or not before deleting scheduled Pods on Node

- export/export.go
- export/export_test.go
- export/mock_export/pod.go
- export/mock_export/pvc.go
- node/mock_node/node.go
- node/node.go
- node/node_test.go
- persistentvolumeclaim/persistentvolumeclaim.go
- persistentvolumeclaim/persistentvolumeclaim_test.go
- pod/pod.go
- pod/pod_test.go
- reset/reset.go
- server/di/di.go
- server/di/interface.go
- server/handler/persistentvolumeclaim.go
- server/handler/pod.go
/kind bug
This PR allows us to specify namespace on manipulation of `Pod` and `PVC`.
In PR #111, we implemented the feature to import from the existing cluster. 
But it is only for the default namespace `default`.
Therefore, we support the different namespace in `import/export`.
Fixes #116
In PR #127 
Since in the WebUI calls the apiserver directly, in this issue, I didn't change that logic. But we must specify a namespace to support this PR's changes. So, I specified a default namespace in `Pod` and `PVC`'s handler.
/assign @sanposhiho
> support namespace in each service

- config/config.go
- config/config_test.go
- docker-compose.yml
- hack/start_simulator.sh
- k8sapiserver/k8sapiserver.go
- server/server.go
- simulator.go
/kind cleanup
/kind feature
Rename the environment variable FRONTEND_URL to CORS_ALLOWED_ORIGIN_LIST and accept list.
Fixes #156 
> Rename the environment variable FRONTEND_URL to CORS_ALLOWED_ORIGIN_LIST and accept list

- node/node.go
- node/node_test.go
- reset/reset.go
/kind bug
Fixed how to specify the namespace in `Reset` function for resources with a namespace.
The current Reset function can't work correctly.
I'm so sorry, this is caused by my fixing of #116.
Relates #84, #116
> Fixed how to specify the namespace in `Reset` function for resources with a namespace

- web/components/TopBar/ResetButton.vue
/kind bug
In the current logic, the `Reset` button returns a success message even if it fails, on the web UI.
Fixed that error handling logic.
Fixes #151
Currently, the behavior check is not exactly finished.
So, this PR should be merged after #162.
/hold
> Fix error handling on calling of reset function on the web UI.

- README.md
- docker-compose.yml
/kind bug
This PR is aimed to fix an issue after installing `
kube-scheduler-simulator` through current docker-compose file. 
If I deploy the simulator on a remote server, it will return errors when requesting `simulator-server` due to wrong request URL, which is quite confusing.
Fixes #
> support external IP in docker-compose.yaml

- simulator/config/config.go
- simulator/export/export.go
- simulator/export/export_test.go
- simulator/export/mock_export/scheduler.go
- simulator/reset/reset.go
- simulator/scheduler/scheduler.go
- simulator/server/di/di.go
- simulator/server/di/interface.go
- simulator/server/handler/schedulerconfig.go
- simulator/simulator.go
- web/components/StoreKey/SchedulerConfigurationStoreKey.ts
- web/components/TopBar/SchedulerConfigurationEditButton.vue
- web/store/schedulerconfiguration.ts
/area web
/kind feature
support external schedulers.
When EXTERNAL_SCHEDULER_ENABLED is given as true, the simulator doesn't start a scheduler and web UI also doesn't show the gear button like this, because we cannot get and change an external scheduler's configuration.
I'll create the doc for users to use an external scheduler later in another PR.
part of #182
> feature(simulator): support an external scheduler

- simulator/scheduler/plugin/resultstore/store.go
- simulator/scheduler/plugin/resultstore/store_test.go
We should make a copy instead of directly mutating the Pod that was sent by the informer.
This fixes a crash in the scheduler (https://github.com/kubernetes/kubernetes/issues/116226), which was trying to concurrently read the same Pod object we mutated.
> Fix crash due to concurrent Pod mutation

- web/components/lib/templates/pod.yaml
**What type of PR is this?**
/kind cleanup
**What this PR does / why we need it**:
This PR replaces all `k8s.gcr.io` references with `registry.k8s.io`. See the linked issue for more details.
**Which issue(s) this PR fixes**:
xref https://github.com/kubernetes/k8s.io/issues/4738
**Release note**:
```
Replace all `k8s.gcr.io` references with `registry.k8s.io`
```
> Replace k8s.gcr.io with registry.k8s.io

- simulator/scheduler/plugin/plugins.go
- simulator/scheduler/scheduler.go
/kind bug
The final score doesn't change after editing the weight of score plugins in scheduler configuration, because result store doesn't read weight from scheduler configuration.
Moreover, following the guide in [https://github.com/kubernetes-sigs/kube-scheduler-simulator/tree/master/simulator/docs/how-to-use-custom-plugins](url), if user doesn't set weight in `OutOfTreeScorePlugins()`, the final score of custom plugin will be always 0 (because weight in scheduler configuration does not take effect).
Fixes #
I fixed this bug by the way. Should I open an issue first?
> Fix a bug that finalscore in pod anno does not comply with weight in sche-config

- simulator/scheduler/plugin/wrappedplugin.go
- simulator/scheduler/plugin/wrappedplugin_test.go
/kind bug
Some wrappedPlugin returns nonsuit status if it does not support the extension point.
This caused the first and subsequent plugins to no called if more than one plugin was set for that extension point. This caused the first and subsequent plugins to no called if more than one plugin was set for that extension point.
Fixes #
/assign @sanposhiho
> BugFix: some wrappedPlugin returns non suit status

- simulator/scheduler/extender/mock_extender/resultstore.go
- simulator/scheduler/extender/resultstore/resultstore.go
- simulator/scheduler/extender/resultstore/resultstore_test.go
- simulator/scheduler/plugin/resultstore/store.go
- simulator/scheduler/plugin/resultstore/store_test.go
- simulator/scheduler/storereflector/annotation.go
- simulator/scheduler/storereflector/mock_storereflector/resultstore.go
- simulator/scheduler/storereflector/storereflector.go
- simulator/scheduler/storereflector/storereflector_test.go
/kind feature
So far, we only record the latest scheduling result. 
This PR store the past ones in `scheduler-simulator/result-history` annotation in a list.
This PR doesn't delete the previous annotations, they'll remain as showing the latest results.
Fixes #214
annotation gonna be like:
```
scheduler-simulator/result-history: >-
[{"scheduler-simulator/bind-result":"{}","scheduler-simulator/filter-result":"{\"node-6jp9b\":{\"AzureDiskLimits\":\"passed\",\"EBSLimits\":\"passed\",\"GCEPDLimits\":\"passed\",\"InterPodAffinity\":\"passed\",\"NodeAffinity\":\"passed\",\"NodeName\":\"passed\",\"NodePorts\":\"passed\",\"NodeResourcesFit\":\"Insufficient
memory\",\"NodeUnschedulable\":\"passed\",\"NodeVolumeLimits\":\"passed\",\"PodTopologySpread\":\"passed\",\"TaintToleration\":\"passed\",\"Volu …
```
> feature(simulator): store previous scheduling result as a result history

- cloudbuild.yaml
/kind cleanup
The job for the cloudbuild reaches the timeout.
> ERROR: (gcloud.builds.submit) build 1953dd53-f30b-4818-9584-98782c34fd42 completed with status "TIMEOUT"
https://storage.googleapis.com/kubernetes-jenkins/logs/post-kube-scheduler-simulator-push-images/1644948577367101440/build-log.txt
Fixes #
> extend cloudbuild timeout

- simulator/go.mod
/kind bug
We cannot import the simulator from the external repository due to the wrong version in go.mod.
We didn't notice it so far because we use `replace` in go.mod. 😓  So, it's only the bug happening when we try to import the simulator from external repo.
Fixes #296
> fix(deps): modify wrong version on go.mod

- OWNERS
Adding new sig member @196Ikuchil as an approver for this repository.
Fixes #
- member for at least 3 months: [Since 11st Apr 2022](https://github.com/kubernetes/org/issues/3346)
- Primary reviewer for at least 10 PRs to the codebase: [Reviewed 22 PRs](https://github.com/kubernetes-sigs/kube-scheduler-simulator/pulls?q=is%3Apr+-author%3A196Ikuchil+reviewed-by%3A196Ikuchil)
- Reviewed or merged at least 20 substantial PRs to the codebase: [38 merged PRs](https://github.com/kubernetes-sigs/kube-scheduler-simulator/pulls/196Ikuchil)
/assign @sanposhiho 
> Add 196Ikuchil to approvers

- web/api/v1/pod.ts
- web/api/v1/pvc.ts
/area web
I am trying to integrate kube-scheduler-simulator with a real Kubernetes cluster. And I found the correct API to retrieve all pods is api/v1/pods instead of api/v1/namespaces//pods in some versions of kube-apiserver.
```
$ curl http://localhost:3131/api/v1/namespaces//pods
<a href="/api/v1/namespaces/pods">Moved Permanently</a>.
```
```
$ curl http://localhost:3131/api/v1/pods
{
"kind": "PodList",
"apiVersion": "v1",
"metadata": {
"resourceVersion": "121823"
},
"items": [
{
"metadata": {
"name": "nginx-pod",
"namespace": "default",
"uid": "44b6bc4e-ad5e-4794-94ed-2879d2d05486",
"resourceVersion": "57267",
"creationTimestamp": "2023-07-21T16:22:52Z",
...
```
So i thinks replacement `api/v1/namespaces//pods` with `api/v1/pods` is a good way.
Fixes #312 #290 
/label …
> Replace api/v1/namespaces//pods with api/v1/pods

- simulator/docs/sample/nodenumber/plugin.go
/kind cleanup
In the NodeNumber example, `klog.Info` was used when `klog.InfoS` was meant to be used.
NONE
> Use correct log function in NodeNumber

- web/components/ResourceBar/ResourceBar.vue
- web/components/TopBar/ImportButton.vue
- web/components/lib/template.ts
/area web
Linter raised errors about unknown type assertions like below.
```
[13:26:01]  ERROR  ERROR in components/lib/template.ts:15:5
TS2322: Type 'unknown' is not assignable to type 'V1Pod'.
13 |   if (process.env.POD_TEMPLATE) {
14 |     const temp = yaml.load(process.env.POD_TEMPLATE);
> 15 |     return temp;
|     ^^^^^^^^^^^^
16 |   }
17 |   return {};
18 | };
```
Added to specify the type
Fixes #
> 【WebUI】Fix errors raised by linter

- Makefile
When running make docker_down, we want to delete the Volume of etcd. So we use the `--volumes`.
```
docker-compose down --volumes
```
Fixes https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/315
> fix: delete volumes when make docker_down

- simulator/docs/custom-plugin.md
- simulator/scheduler/config/plugin.go
/kind bug
Before this PR, users had to register their custom plugin names in `registeredOutOfTreeMultiPointName`. 
This is undocumented and led to this kind of issue: https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/311.
This PR eliminates the need to register `registeredOutOfTreeMultiPointName` in the first place, rather than documenting the existence of `registeredOutOfTreeMultiPointName`.
Fixes #311
> fix: reduce the places where users have to register for using custom plugins

- simulator/pkg/debuggablescheduler/debuggable_scheduler.go
/kind cleanup
Before this PR, the simulator attempts to load a default kubeconfig event if a kubeconfig is passed.
This PR removes this waste. 
Fixes #336
> Not trying to load a default kubeconfig when a kubeconfig is passed

- Makefile
- simulator/docs/running-simulator.md
/kind cleanup
Nowadays, we don't need to install `docker-compose`. We can use `docker compose` instead of that.
Also, it means we use docker compose v2, however as far as I know, it doesn't affect our use cases.
https://docs.docker.com/compose/migrate/
None
> Use docker compose instead of docker-compose

- simulator/docs/custom-plugin.md
Just clarify import is required for nodenumber, which is obvious for those who know Golang well, but people might forget.
ref #341
> clarify the import is required

- simulator/config/config.go
/kind bug
Before this PR, when `externalImportEnabled` is set true it loads kubeconfig by `GetKubeClientConfig`. It loads kubeconfig in the default directories (ref: https://pkg.go.dev/k8s.io/client-go/tools/clientcmd#pkg-overview).
This PR fixes it to load kubeconfig at the specified path of `kubeConfig`.
Fixes #354 
> Fix to load kubeconfig specified by simulator server configuration

- simulator/pkg/debuggablescheduler/debuggable_scheduler.go
Add related area tag(s):
Add one of the following kinds:
/kind bug
The `debuggableScheduler` aims to load the default configuration when no explicit `configfile` is provided. However, the current condition to check the `configFile` fails because it only verifies if the pointer is `nil`. When the pointer contains an empty string, it bypasses the default config loading logic.
To address this issue, we have added a new condition to check whether the value of `configFile` is an empty string, ensuring the default configuration is loaded as expected when no config file is specified.
Fixes https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/375
I'm preparing a presentation about kube-scheduler in Taiwan this week, I would like to use …
> Fix Default Config Loading When ConfigFile Is Not Specified

- OWNERS
I never had any significant involvement in this repo and expect to have less chances of involvement in the future.
Fixes #
> Remove alculquicondor and Huang-Wei from OWNERS

- cloudbuild.yaml
/kind feature
We need a new container for the debuggable scheduler.
Fixes #384
> feat: add debuggable-scheduler at cloudbuild

- compose.local.yml
A fix for `make docker_up_local` and `make docker_down_local` due to invalid empty fields in `compose.local.yaml`.
/kind bug
Running the following command `make docker_up_local` results in an error:
```
$ make docker_down_local         
docker compose -f compose.yml -f compose.local.yml down --volumes
validating /Users/zele/Projects/go-k8s-wasm/dejanzele/kube-scheduler-simulator/compose.local.yml: services.simulator-cluster must be a mapping
make: *** [Makefile:77: docker_down_local] Error 15
```
Docker compose complains about empty fields in the `services` block defined like the following:
```
services:
init-container:
```
This PR just adds empty objects to the affected fields
Fixes #
> fix: invalid empty services fields in compose.local.yml

- simulator/server/handler/schedulerconfig.go
/kind feature
Even though the `Extender` documentation mentioned the ability to add `extenders` to the scheduler configuration via the Web UI, this wasn't actually supported.
> feat: allow user to configure extenders via web UI

- simulator/pkg/debuggablescheduler/command.go
- simulator/pkg/debuggablescheduler/debuggable_scheduler.go
bug
Lack of adding user-defined plug-in configuration to defaultpls, resulting in loss of user configuration
Fixes # Safeguard user expectations
> fix(simulator): register the out-of-tree plugins before initializing configurations

- keps/140-scenario-based-simulation/README.md
/area scenario
/kind cleanup
- Fixes in-page links in Scenario KEP
- Fixes outdated function and constant names in Scenario KEP
- I am not 100% sure I did the correct fix. Please let me know if wrong
Fixes #
> Fix links and outdated function/constant names in Scenario KEP

- compose.yml
- simulator/cmd/simulator/simulator.go
- simulator/docs/import-cluster-resources.md
- simulator/resourceapplier/resource.go
- simulator/resourceapplier/resourceapplier.go
- simulator/resourceapplier/resourceapplier_test.go
- simulator/server/di/di.go
- simulator/syncer/syncer.go
- simulator/syncer/syncer_test.go
/kind cleanup
`syncer` and `oneshotimporter` have their own logic of applying resources. They can be generalized and the replaying feature (#395) can use it.
This PR separates that of `syncer` and makes it a module `resourceapplier`.
Part of #395 
I'll create another PR to refactor `oneshotimporter` to use `resourceapplier`.
> Separate the logic of applying resources from syncer and make it reusable

- simulator/docs/import-cluster-resources.md
This PR adds a troubleshooting section to the `import-cluster-resources.md` documentation to address client rate limiter errors that users encounter when importing resources from large clusters.
**Changes made:**
- Added a new "Troubleshooting" section with subsection "Client Rate Limiter Errors"
- Explained the root cause: default QPS (5) and Burst (10) settings are too low for large cluster imports
- Documented the automatic solution: simulator sets QPS to 400 and Burst to 1200 in code
- Clarified that no manual kubeconfig modification is required
This improvement helps users understand why they might see "context deadline" errors and reassures them that the simulator handles this automatically.
Fixes #420
This is a documentation-only change that …
> Fix issue #420: Add troubleshooting section for client rate limiter errors in import-cluster-resources
