- SECURITY_CONTACTS
> Fix: typo on SECURITY_CONTACTS

- server/di/di.go
Hello. This PR adds more docs on package di.
/cc @adtac
> docs: add more docs on package di

- OWNERS
Hi team. I want to add me to reviewers on this repo if it is OK. 
This repo doesn't have enough reviewers.
/cc @adtac
/cc @Huang-Wei
/cc @alculquicondor
> Add sanposhiho on reviewers

- scheduler/scheduler.go
Thank you for your support and guidance.
Fix #11
> Updated restart scheduler for restore old setting

- .github/workflows/PULL_REQUEST_TEMPLATE.md
This PR adds pull request template.
Most of them are the same as the template in k/k.
https://github.com/kubernetes/kubernetes/blob/master/.github/PULL_REQUEST_TEMPLATE.md
> add pull request template

- docs/api.md
- scheduler/scheduler.go
- server/di/interface.go
- server/handler/schedulerconfig.go
- server/server.go
/kind feature
/kind api-change
Add api to reset scheduler configuration.
Related #26
> add reset scheduler configuration

- simulator.go
/kind feature
I fixed format of error message.
None
> fix error message

- .golangci.yml
- scheduler/plugin/plugins.go
/kind bug
I added prealloc linter.
For more detail is following.
https://github.com/alexkohler/prealloc
I think this linter rule makes this project better.
None
> add prealloc linter and fix detected target

- docs/api.md
- priorityclass/priorityclass.go
- server/di/di.go
- server/di/interface.go
- server/handler/priorityclass.go
- server/server.go
Added Service Layer Interface, Service, Handler, DI to container, as well as the handler and paths to the server.
Can I have some guidance on how to test and possible next steps? Thank you
> support PriorityClass on backend

- cloudbuild.yaml
/kind bug
my mistake. docker image for frontend should be built in `./web` dir.
Ref #19 
> change context for frontend build

- k8sapiserver/k8sapiserver.go
- scheduler/scheduler.go
/kind bug
I fixed klog format.
I replace klog.Info to klog.Infof to display error message.
None
> fix klog format

- README.md
Add initial configuration description on README
Fixes #37
> add initial config description on README

- scheduler/plugin/plugins.go
- scheduler/plugin/plugins_test.go
/kind bug
Scores from NormalizedScore are not recorded correctly, because `simulatorPlugin.ScoreExtensions()` returns internal plugins's `ScoreExtensions()`. We should use `simulatorPlugin.NormalizeScore()` in ScoreExtension, so should return simulatorPlugin itself.
Fixes #89
> Run NormalizeScore correctly

- docs/api-samples/v1/README.md
- docs/api.md
/kind deprecation
There are some small mistakes in the docs added in PR #64.
This PR fixes it.
Fixes #92
Relates #64
> Fix missing links on doc

- web/pages/index.vue
/kind bug
We import `PriorityClassList`component on`index.vue`.
(Why was it working all this time?)
No fixes.
/assgin @sanposhiho
> Import `PriorityClassList` component on `index.vue` explicitly

- scheduler/plugin/plugins.go
- scheduler/plugin/plugins_test.go
- scheduler/scheduler_test.go
/kind cleanup
Rename `simulatorPlugin` to `wrappedPlugin`.
Fixes #124
Is this problem correctly fixed as you intended with this change?
/assign @sanposhiho
> Rename simulatorPlugin to wrappedPlugin

- hack/start_simulator.sh
Hello team.
This PR enable to check if etcd is on path in start_simulator.sh.
> Enable to check if etcd is on path in start_simulator.sh

- .dockerignore
Add one of the following kinds:
/kind cleanup
Don't rebuild image while only change configuration in `docker-compose.yml`
> fix: add docker-compose.yml to .dockerignore

- CONTRIBUTING.md
- keps/README.md
Introduce internal kep to the project
Fixes #173 
> Introduce internal kep to the project

- web/api/v1/node.ts
- web/api/v1/pod.ts
- web/api/v1/priorityclass.ts
- web/api/v1/pv.ts
- web/api/v1/pvc.ts
- web/api/v1/storageclass.ts
- web/components/ResourceAddButton.vue
- web/components/lib/template.ts
- web/components/lib/templates/node.yaml
- web/components/lib/templates/pod.yaml
- web/components/lib/templates/priorityclass.yaml
- web/components/lib/templates/pv.yaml
- web/components/lib/templates/pvc.yaml
- web/components/lib/templates/storageclass.yaml
- web/store/node.ts
- web/store/pod.ts
- web/store/priorityclass.ts
- web/store/pv.ts
- web/store/pvc.ts
- web/store/storageclass.ts
/kind bug
Use metadata.generateName instead of metadata.name with ordinal suffix. Avoid name collisions when resources are created, deleted and created again, e.g.:
* New Pod + Apply -> (the pod name will be `pod1`)
* New Pod + Apply  -> (the pod name will be `pod2`)
* Delete `pod1`
* New Pod + Apply (the name will be `pod2`) <- `pod2` already exists.
Fixes #166 
> [Frontend] Use GenerateName instead of Name in resource templates

- simulator/Makefile
/kind bug
/priority important-soon
`make openapi` command has been removed from `Makefile`.
Re-added it.
Fixes #193 
/label
> Update Makefile to add PHONY `openapi`

- simulator/.golangci.yml
- simulator/config/config.go
- simulator/export/export.go
- simulator/export/export_test.go
- simulator/go.mod
- simulator/node/node_test.go
- simulator/replicateexistingcluster/mock_replicateexistingcluster/export.go
- simulator/replicateexistingcluster/replicateexistingcluster.go
- simulator/replicateexistingcluster/replicateexistingcluster_test.go
- simulator/scheduler/plugin/plugins.go
- simulator/scheduler/plugin/resultstore/store.go
- simulator/scheduler/plugin/resultstore/store_test.go
- simulator/scheduler/plugin/wrappedplugin.go
- simulator/scheduler/plugin/wrappedplugin_test.go
- simulator/scheduler/scheduler.go
- simulator/scheduler/scheduler_test.go
- simulator/server/di/di.go
- simulator/server/di/interface.go
- simulator/server/handler/export.go
- simulator/server/handler/reset.go
- simulator/server/handler/schedulerconfig.go
- simulator/server/server.go
- simulator/simulator.go
/kind cleanup
Kubernetes community has the official domain for sigs repos: "sigs.k8s.io/XXXXXX".
This repo doesn't use that domain, but almost all other repos are using this as go module name. let's rename our module.
Fixes #
Sorry, this PR also causes many conflicts to everyone's PRs. 😓
> Rename module to sigs.k8s.io/kube-scheduler-simulator/simulator

- RELEASE.md
This PR adds release guide for this project. I referred to the release guide in scheduler-plugins.
https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/RELEASE.md
Fixes #
> Add release guide

- OWNERS
Adding new sig member @196Ikuchil as a reviewer for this repository.
Fixes #
- member for at least 3 months: [Since 11st Apr 2022](https://github.com/kubernetes/org/issues/3346)
- Primary reviewer for at least 5 PRs to the codebase: [Reviewed 11 PRs](https://github.com/kubernetes-sigs/kube-scheduler-simulator/pulls?q=is%3Apr+-author%3A196Ikuchil+reviewed-by%3A196Ikuchil)
- Reviewed or merged at least 20 substantial PRs to the codebase: [47 merged PRs](https://github.com/kubernetes-sigs/kube-scheduler-simulator/pulls?q=is%3Apr+author%3Asanposhiho)
I'll try harder:-)
/assign @sanposhiho 
> Add 196Ikuchil to reviewers

- .github/PULL_REQUEST_TEMPLATE.md
I just created new tags for each project. (area/web, area/simulator, area/scenario)
PRs should have these tags if related to specific area.
Fixes #
> fix(PULL_REQUEST_TEMPLATE): Add area tags

- simulator/Dockerfile
/kind cleanup
No need to continue to build that with go v1.16.
Fixes #
> update(simulator): golang v1.19

- web/.eslintrc.js
- web/api/APIProvider.vue
- web/api/APIProviderKeys.ts
- web/api/v1/watcher.ts
- web/components/ResourceViews/DataTables/NodeDataTable.vue
- web/components/ResourceViews/DataTables/PVCDataTable.vue
- web/components/ResourceViews/DataTables/PVDataTable.vue
- web/components/ResourceViews/DataTables/PodDataTable.vue
- web/components/ResourceViews/DataTables/PriorityClassDataTable.vue
- web/components/ResourceViews/DataTables/StorageClassDataTable.vue
- web/components/ResourceViews/Lists/NodeList.vue
- web/components/ResourceViews/Lists/PVCList.vue
- web/components/ResourceViews/Lists/PVList.vue
- web/components/ResourceViews/Lists/PodList.vue
- web/components/ResourceViews/Lists/PriorityClassList.vue
- web/components/ResourceViews/Lists/StorageClassList.vue
- web/components/ResourceViews/Lists/UnscheduledPodList.vue
- web/components/ResourceWatcher.vue
- web/components/TopBar/ImportButton.vue
- web/components/TopBar/ResetButton.vue
- web/pages/index.vue
- web/store/helpers/storeHelper.ts
- web/store/node.ts
- web/store/pod.ts
- web/store/priorityclass.ts
- web/store/pv.ts
- web/store/pvc.ts
- web/store/storageclass.ts
- web/types/api/v1.ts
- web/types/resources.ts
/kind feature
Changed frontend to automatically update resource information using `/api/v1/listwatchresource` API.
Fixes #120
This PR relates to PR #165. That PR implements the `/listwatchresource` API which is used in this PR.
> Implement to update all resources periodically on Frontend

- .gitignore
- README.md
- simulator/docs/env-variables.md
As part of this PR, we are adding documentation for environment variables that are used to configure kube-scheduler-simulator
Fixes #106 
> Improve documentation about environment variables being used

- simulator/docs/how-to-use-custom-plugins/README.md
It corrects the references in how-to-use-custom-plugins docs.
Fixes #
> fix(doc): fix the references in how-to-use-custom-plugins

- simulator/docs/how-to-use-custom-plugins/nodenumber/plugin.go
/kind bug
The custom plugin example may not run as expected, this PR will fix it.
Fixes #238
> Fix custom plugin example of nodenumber

- simulator/docs/env-variables.md
- simulator/pod/pod.go
> fix a typo

- README.md
Signed-off-by: kerthcet <kerthcet@gmail.com>
/kind cleanup
Fixes #
NONE
> Fix several typos in readme

- web/README.md
Signed-off-by: yanghesong <hesong.yang@foxmail.com>
/area web
Add node version in README.md of web.
Fixes #
> Add node version in README.md of web.

- simulator/docs/api.md
Update WatchEvent URL in simulator/docs/api.md.
Signed-off-by: yanghesong <hesong.yang@foxmail.com>
Fixes #
> Update WatchEvent URL.

- web/package.json
Add prettier directory for web. prettier --write won't work without dot.
Fix #235
Signed-off-by: yanghesong <hesong.yang@foxmail.com>
/area web
/kind bug
Fixes #
> Add prettier directory for web.

- web/components/ResourceWatcher.vue
- web/tsconfig.eslint.json
Format web code.
Signed-off-by: yanghesong <hesong.yang@foxmail.com>
/area web
Fixes #235
> Format web code.

- simulator/k8sapiserver/k8sapiserver.go
This is equivalent to passing `--allow-privileged` to kube-apiserver. It is needed for any simulations that include privileged Pods, and it shouldn't have any effect on simulations without such Pods.
Fixes #
> Configure kube-apiserver to allow privileged containers.

- web/components/ResourceAddButton.vue
- web/components/ResourceBar/ResourceBar.vue
- web/components/ResourceBar/SchedulingResults.vue
- web/components/ResourceViews/DataTables/NodeDataTable.vue
- web/components/ResourceViews/DataTables/PVCDataTable.vue
- web/components/ResourceViews/DataTables/PVDataTable.vue
- web/components/ResourceViews/DataTables/PodDataTable.vue
- web/components/ResourceViews/DataTables/PriorityClassDataTable.vue
- web/components/ResourceViews/DataTables/StorageClassDataTable.vue
- web/components/ResourceViews/Lists/NodeList.vue
- web/components/ResourceViews/Lists/PVCList.vue
- web/components/ResourceViews/Lists/PVList.vue
- web/components/ResourceViews/Lists/PodList.vue
- web/components/ResourceViews/Lists/PriorityClassList.vue
- web/components/ResourceViews/Lists/StorageClassList.vue
- web/components/ResourceViews/Lists/UnscheduledPodList.vue
- web/components/Snackbar.vue
- web/components/TopBar/ExportButton.vue
- web/components/TopBar/ImportButton.vue
- web/components/TopBar/ResetButton.vue
- web/components/TopBar/SchedulerConfigurationEditButton.vue
- web/store/node.ts
- web/store/pod.ts
- web/store/priorityclass.ts
- web/store/pv.ts
- web/store/pvc.ts
- web/store/schedulerconfiguration.ts
- web/store/storageclass.ts
/area web
/kind bug
Fix some error messages to avoid `TypeError` occurring.
These XXXKey variables are a `Symbol`type and can't covert to a `string` type.
It is unlikely that this throw line will be reached, but as it is now, the following error will occur.
```
TypeError: Cannot convert a Symbol value to a string
```
Fixes #
/ok-to-test
> Fix some error messages to avoid `TypeError` occurring.

- README.md
- simulator/docs/env-variables.md
This PR adds documentation for the function of existing cluster importing. 
Fixes #41
> Documentation for existing cluster importing

- simulator/scheduler/storereflector/storereflector.go
This fixes the following error seen in logs:
```
storereflector.go:93] failed to update the pod with retry to record store: update pod:
sigs.k8s.io/kube-scheduler-simulator/simulator/scheduler/storereflector.(*reflector).storeAllResultToPodFunc.func1.1
/go/src/simulator/scheduler/storereflector/storereflector.go:88
- Operation cannot be fulfilled on pods "[redacted]": the object has been modified; please apply your changes to the latest version and try again
```
Fixes #
> storeAllResultToPodFunc: Retry on version conflict

- simulator/Dockerfile
- simulator/config/config.go
- simulator/docs/environment-variables.md
- simulator/docs/simulator-server-config.md
/kind bug
Pass the config file to the docker image so that it'll be loaded correctly in docker env.
Fixes #280
> fix: pass the configuration file from build-env

- README.md
Fix to README documentation.
It fix minor broken links in README.md file and also add namespace as Resource in documentation as it is added recently.
Fixes #
No additional feature/issue resolved in this PR. Only minor documentation fix added.
> Fix broken links and missing details in README

- OWNERS
/kind cleanup
Remove @adtac from the OWNER; no much recent activities from him.
Thanks for taking my mentor in GSoC 2021.
I wouldn't be here and wouldn't be the contributor on k/k as well
if I had not gone through a great GSoC with you.
Fixes #
/cc @alculquicondor 
> remove adtac from OWNERS

- Makefile
- README.md
- docker-compose-local.yml
- simulator/docs/external-scheduler.md
- simulator/docs/import-cluster-resources.md
- simulator/docs/running-simulator.md
/kind feature
- update doc to run the simulator pulling images from the registry
- add docker-compose.yml to run simulator by pulling images from the registry
- simplify README and move some parts to other docs.
Fixes #293 
> fix: update the documentation to run the simulator by pulling images from the registry

- simulator/docs/extender.md
/kind cleanup
I missed very very small nit on #302
Fixes 
> Fix config version on extender docs

- docker-compose.yml
/kind feature
update the image tag to v0.1.1. After this PR, I'll soon release simulator/v0.1.1
Fixes #
> update the image tag to v0.1.1

- simulator/scheduler/storereflector/storereflector.go
- simulator/scheduler/storereflector/storereflector_test.go
/kind cleanup
package  is being imported more than once
Fixes #
> chore: pkg imported more than once

- docker-compose-local.yml
- docker-compose.yml
> Bump etcd to v3.4.26

- Makefile
/add simulator
add `make docker_down_local`
Fixes #
> add `make docker_down_local`

- simulator/scheduler/plugin/plugins.go
Fix function naming typo from `applyPluingSet` to `applyPluginSet`
Fixes #
> Fix function naming typo

- simulator/Dockerfile
/kind bug
The golang version in Dockerfile is too old and it's not built correctly.
Fixes #
> Update golang to v1.21 in Dockerfile

- simulator/.golangci.yml
/kind cleanup
Deleted linter had been deprecated since v1.48 and v1.49.
So I delete these.
Fixes #
> delete: deprecated linters

- simulator/Dockerfile
- simulator/go.mod
> Bump Go 1.22

- simulator/docs/import-cluster-resources.md
/kind cleanup
The path was wrong.
Fixes #
> Modify the path on the document

- README.md
- RELEASE.md
- docker-compose.yml
/kind feature
Update docker-compose for -
https://github.com/kubernetes-sigs/kube-scheduler-simulator/releases/tag/simulator%2Fv0.2.0
Also update the release doc.
Fixes #
> update docker-compose.yml with v0.2.0

- simulator/pkg/debuggablescheduler/debuggable_scheduler.go
/kind bug
Resolve error when config flag is empty.
Fixes #
> : handle the case when the config option is not specified

- simulator/docs/import-cluster-resources.md
Change yaml to point to correct config
None
> correct an example config on import-cluster-resources.md

- simulator/cmd/scheduler/Dockerfile
- simulator/cmd/simulator/Dockerfile
/kind cleanup
As the title says
ref: https://medium.com/@marcin.niemira/optimise-docker-build-for-go-c03d6eb8b4b
None
> Optimize Dockerfiles to reduce the time needed to build

- simulator/config/config.go
/kind cleanup
just a cleanup, see #348.
Fixes #348
> Update the doc for CORS_ALLOWED_ORIGIN_LIST

- cloudbuild.yaml
/kind cleanup
For fixing the main branch 
Fixes #
> Use buildx in Cloud Build to use the build cache

- simulator/cmd/simulator/simulator.go
- simulator/config.yaml
- simulator/config/config.go
- simulator/config/v1alpha1/types.go
- simulator/docs/import-cluster-resources.md
- simulator/docs/simulator-server-config.md
- simulator/server/di/di.go
- simulator/server/di/interface.go
- simulator/syncer/resource.go
- simulator/syncer/syncer.go
- simulator/syncer/syncer_test.go
/kind feature
This PR implements syncer that continuously sync the simulator cluster's resources to an external cluster's ones.
Fixes #327
This PR is too large, but it's difficult to break down it because of testing. Please see this commit by commit: 
- implement syncer: https://github.com/kubernetes-sigs/kube-scheduler-simulator/commit/82a49436fff4845c0812244f0e9f244d0ff9cecb
- add syncer to the di container and invoke it from the entry point: https://github.com/kubernetes-sigs/kube-scheduler-simulator/commit/c844916117a2203526ecba417d5f5c92e69353e8
> Implement syncer

- RELEASE.md
> Update RELEASE.md to replace a dead link

- docker-compose.yml
/kind feature
Update docker-compose.yml for a new release, v0.3.0
Fixes #
> Update docker-compose.yml for v0.3.0

- simulator/docs/api.md
`ResourcesForImport` no longer exists. 
The current import of Config is performed by `ResourcesForLoad`, so these link should be updated
Fixes #
> Fix 404 errors in API reference

- compose.local.yml
- compose.yml
/area web
/kind feature
v0.4.0 is released, let's move our docker compose to use them.
Fixes #
> fix: update the docker composer file to load v0.4.0

- compose.local.yml
- simulator/docs/sample/plugin-extender/docker-compose.yaml
- web/Dockerfile
/kind cleanup
A few warnings appear when running the various `docker_*` make targets because of deprecated syntax.
> fix: update Docker files to avoid warnings

- simulator/go.mod
- simulator/go.sum
- simulator/pkg/debuggablescheduler/debuggable_scheduler.go
- simulator/scheduler/config/wasm.go
- simulator/scheduler/config/wasm_test.go
/kind feature
This PR adds [kube-scheduler-wasm-extension](https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension) support into the simulator via the debuggable scheduler. This allows easy testing of WASM plugins by simply adding the required entries to the scheduler config.
> feat: support the wasm extension in the debuggable scheduler

- Makefile
/kind bug
`make tools` are not working correctly.
This is due to the fact that the `GOPATH` is not being read correctly
```sh
% make tools
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /bin v1.55.2
golangci/golangci-lint info checking GitHub for tag 'v1.55.2'
golangci/golangci-lint info found version: 1.55.2 for v1.55.2/darwin/amd64
^Xinstall: /bin//golangci-lint: Operation not permitted
make: *** [tools] Error 71
```
Fixes #
If the problem is only on my local, please close it.
> Fixes to the read way of GOPATH on Makefile

- Makefile
- simulator/.golangci.yml
- simulator/cmd/simulator/simulator.go
- simulator/resourcewatcher/eventproxy.go
- simulator/resourcewatcher/eventproxy_test.go
- simulator/scheduler/extender/extender_test.go
- simulator/scheduler/extender/service_test.go
- simulator/scheduler/plugin/wrappedplugin.go
- simulator/scheduler/plugin/wrappedplugin_test.go
- simulator/scheduler/storereflector/storereflector.go
- simulator/snapshot/snapshot_test.go
/kind cleanup
We're using go1.22 but golangci-lint supports it since v1.56.0 (https://github.com/golangci/golangci-lint/issues/4273). We're using v1.55.2 so we need to upgrade it.
Fixes #
> chore: upgrade golangci-lint to 1.64.5

- RELEASE.md
The mailing list is migrated
Related: https://github.com/kubernetes/community/issues/8437
> fix: update the mailing list address

- simulator/scheduler/storereflector/storereflector.go
- simulator/scheduler/storereflector/storereflector_test.go
/kind bug
Delete old annotations when annotation string exceeds 256KB
Fixes #417 
> fix: trim the history annotation when the size is too big
